
### Examining racial discrimination in the US job market

#### Background
Racial discrimination continues to be pervasive in cultures throughout the world. Researchers examined the level of racial discrimination in the United States labor market by randomly assigning identical résumés black-sounding or white-sounding names and observing the impact on requests for interviews from employers.

#### Data
In the dataset provided, each row represents a resume. The 'race' column has two values, 'b' and 'w', indicating black-sounding and white-sounding. The column 'call' has two values, 1 and 0, indicating whether the resume received a call from employers or not.

Note that the 'b' and 'w' values in race are assigned randomly to the resumes.

#### Exercise
You will perform a statistical analysis to establish whether race has a significant impact on the rate of callbacks for resumes.

Answer the following questions **in this notebook below and submit to your Github account**. 

   1. What test is appropriate for this problem? Does CLT apply?
   2. What are the null and alternate hypotheses?
   3. Compute margin of error, confidence interval, and p-value.
   4. Discuss statistical significance.

You can include written notes in notebook cells using Markdown: 
   - In the control panel at the top, choose Cell > Cell Type > Markdown
   - Markdown syntax: http://nestacms.com/docs/creating-content/markdown-cheat-sheet


#### Resources
+ Experiment information and data source: http://www.povertyactionlab.org/evaluation/discrimination-job-market-united-states
+ Scipy statistical methods: http://docs.scipy.org/doc/scipy/reference/stats.html 
+ Markdown syntax: http://nestacms.com/docs/creating-content/markdown-cheat-sheet

****

### Question 1

We have two binomial variables which approach normal variables for large $np$ and $n(1-p)$. The rule of thumb is $np > 10$ and $n(1-p) > 10$. As we see, our lowest count is 157, so the Central Limit Theorem is valid:  

In [2]:
import pandas as pd
import numpy as np
from scipy import stats
import math 
data = pd.io.stata.read_stata('data/us_job_market_discrimination.dta')

Obs_bc, Obs_bn = sum(data[data.race=='b'].call), sum(data.race=='b') - sum(data[data.race=='b'].call)
Obs_wc, Obs_wn = sum(data[data.race=='w'].call), sum(data.race=='w') - sum(data[data.race=='w'].call)

Obs_b, Obs_w = Obs_bc+Obs_bn, Obs_wc+Obs_wn
Obs_tot = Obs_b + Obs_w
Obs_arr = np.array([[Obs_bc, Obs_bn],[Obs_wc, Obs_wn]])

p_b, p_w = Obs_bc/Obs_b, Obs_wc/Obs_w

print Obs_bc, Obs_bn, p_b
print Obs_wc, Obs_wn, p_w

157.0 2278.0 0.064476386037
235.0 2200.0 0.0965092402464


So we can use a z-test.

### Exercise 2

We want to compare the difference in proportions, $p_b-p_w$, to zero. Since we suspect that black applicants are discriminated against, we should use the null hypothesis that $p_b-p_w \le 0$ and an alternate hypothesis of $p_b-p_w>0$.

### Question 3

Computations:

In [27]:
var_b = p_b*(1-p_b)/Obs_b
var_w = p_b*(1-p_w)/Obs_w
sig = math.sqrt(sig_b + sig_w)
me = sig*stats.norm.ppf(0.975)
print "The margin of error is: " + str(me)
mdiff = p_b-p_w

print "The 95% confidence interval is: [ " + str(mdiff-me)+ ", " + str(mdiff+me) + " ]"

z = abs(mdiff/sig)
print "The p-value is: " + str(1-stats.norm.cdf(z))


The margin of error is: 0.0136770209928
The 95% confidence interval is: [ -0.0457098752023, -0.0183558332166 ]
The p-value is: 2.21179825988e-06


### Question 4

The above calculations strongly support the alternate hypothesis. We are 95% confident that the call-back rate for black applications is between 1.84 and 4.57 percent worse than for white applicants. Conversely, if call-backs were truly color-blind, there is only a 0.0002212 percent chance that we would see data as extreme as we have.

Note that our conclusions assume no sampling bias. Firstly, color assignment of resumes must have been blind to actual merit of the resumes. Also, the companies to which resumes were sent must have sampled randomly. 

